### ISSUE TITLE
Standardize on "orangered" for code

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/tr-design#116]
ReSpec-generated specs and WHATWG specs both use color "orangered" for `code`. I wonder if we could add that to base.css?

**Comment by plehegar** [comment]
@tabatkins , got an opinion on this one?

**Comment by tabatkins** [comment]
WHATWG only does this for `code.idl`. They use gray(40%) for generic `code`.

I don't have a strong opinion on whether to use it like this or not.  I defer to whoever's got more ownership over the overall design efforts, which I think is @fantasai (channelling Divya or @LeaVerou ).

**Comment by LeaVerou** [comment]
Any links to examples of this in practice?

**Comment by marcoscaceres** [comment]
Example of [W3C spec](https://www.w3.org/TR/payment-request/) - showing in ToC and inline (plus in WebIDL):

![screenshot 2017-05-30 16 11 09](https://cloud.githubusercontent.com/assets/870154/26570242/c0cf78ee-4552-11e7-803e-8ab11c4a5cb3.png)


Example of [WHATWG spec](https://fetch.spec.whatwg.org) (showing inline usage):

![screenshot 2017-05-30 16 11 54](https://cloud.githubusercontent.com/assets/870154/26570255/d3c51472-4552-11e7-9879-8ddbf18722be.png)

**Comment by marcoscaceres** [comment]
Added links to actual specs above.

**Comment by LeaVerou** [comment]
Looks OK to me.

**Comment by fantasai** [comment]
And CSS specs use blue.

I intentionally left out `code` styling from the scope of base.css because there were so many variations on it, and I don't think we have a really clear and desirable styling pattern that I'd want us to copy. (That WebIDL screenshot, for example, is using two different colors for types just within that single box.)

I'd like us to get to a point where we converge on code styling, but I think we're not there yet. It'll require us to know, more definitively, what are all the different types of code styling we need, and it'll require us to have a scheme that works consistently across all of our specs. So I'm gonna close this bug (standardize on code as orangered) as WONTFIX.
