### ISSUE TITLE
Timeline and Considerations 

### ISSUE THREAD

**Issue by jspellman** [w3c/tr-design#16]
As someone who normally uses whatever stylesheet I am given, I was concerned to see that the Proposed Rec that transitions in the fall "should easily allow the W3C Advisory Committee to visualize the document using the new design of the following year".  When will there be test stylesheets for us to test for the upcoming year?  I assume they will be available earlier because the deadline for the direction decision will  be Nov 30 and the webmaster will deploy them on Dec 1 (making him/her work weekends?) .  However, there is no mention of a schedule to provide stylesheets for people transitioning to PR in the fall who want the AC to visualize the final look.

**Comment by plehegar** [comment]
The style sheets will start being available at the end of October, to allow time for folks to review them. The styles are then made final on November 30. PR published late in the fall, ie after October 15, would need to expose the documents with the upcoming new styles because the REC is likely to be published after December 31. If your REC is published in the same year as the PR, there is no concern.
