### ISSUE TITLE
Mobile-friendly Styles / Restrict the Style of <pre> and Tables

### ISSUE THREAD

**Issue by siusin** [w3c/tr-design#20]
This is relevant to #10 

Not sure if it's a general problem for all the mobiles, but the font-size in our specs is always too small to read on my phone (Safari 08, iPhone 5s). Here's a screenshot from /TR/animation-timing:
<img src="https://cloud.githubusercontent.com/assets/5643782/8108369/8798c9d8-1082-11e5-81d5-b64df6da976b.png" width=50% />

It's even more problematic when the style of the pre elements haven't been carefully chosen (screenshot from /TR/resource-timing):
<img src="https://cloud.githubusercontent.com/assets/5643782/8108028/71620e9c-1080-11e5-919f-8f099b7712e2.png" width=50% />

My suggestion'd be: 
- Slightly reduce the margin of the document (less white space in this case, on the contrary to #13 )
- Adjust(increase) the font-size of the titles, the subtitles and the body;
- Restrict the Style of pre elements and Tables, though it isn't easy...

**Comment by tripu** [comment]
Increasing font size and minimising margins is a sensible thing to do on smaller screens; I think it doesn't contradict #13. Thank you for the detailed suggestion.

**Comment by fantasai** [comment]
I think the main problem is that we need to add a viewport meta tag to the output. I'll make sure this is part of the requirements for publishing in 2016, provided webreq is okay with that. It's a minor change to the spec markup / pubrules, so hopefully should be possible.

I did adjust the margins on the document as requested. I'm not so sure about altering <pre> blocks, as making the text wrap there could be more confusing than scrolling. However I will add that rule for printing, so that they don't get clipped. Let me know if there are other things to do. You can test the styles at http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sample
