### ISSUE TITLE
Minor possible additions for paged media

### ISSUE THREAD

**Issue by iherman** [w3c/tr-design#23]
I have recently implemented a service (primarily aimed at documents produced by respec) to [convert TR documents to EPUB3](https://github.com/iherman/respec2epub). In doing so, and having looked at the output in some of the EPUB readers I have access. This resulted in some minor additions to the styling of the document. These are as follows:

```
h2 {
    page-break-before: always;
    page-break-inside: avoid;
    page-break-after: avoid;
  }

  div.head h2 {
    page-break-before: auto;
    page-break-inside: avoid;
    page-break-after: avoid;
  }

  figure {
    page-break-inside: avoid;
  }

  h3, h4, h5 {
    page-break-after: avoid;
  }

  dl dt {
    page-break-after: avoid;
  }

  dl dd {
    page-break-before: avoid;
  }

  div.example, div.note, pre.idl, .warning, table.parameters, table.exceptions {
    page-break-inside: avoid;
  }

  p {
    orphans: 4;
    widows: 2;
  }
```

I realize that some of these are part of the new CSS, but others are not. I think we could consider adding these to the core CSS, thereby avoiding processors like mine having to repeat them.

Note that some of the class selectors may be respec specific. Although the converter seems to work with documents produced by bikeshed, too, I must admit I did not go through all the bikeshed class names to find the corresponding ones, if any.

**Comment by iherman** [comment]
I forgot to add a reference to the [service itself on labs](https://labs.w3.org/epub-generator/); respec simply calls out to this service, the code (which is in Python anyway) is not on the client.

**Comment by fantasai** [comment]
The new styles already had some of these (no breaking after headings and dt, no breaking inside figures), and I added to that no breaking inside headings or dt, and added widows/orphans: 2. (4 seemed a little too stringent).

I didn't add force breaks after h2, because when printing specs I usually don't want so many page breaks, even if that's nice for an EPub edition. Similarly, I'm not convinced that for long notes/examples/etc we necessarily want to leave a giant gap instead of allowing the box to break across pages, so I did not add that page-break-inside rule.

Feel free to reopen if you have anything to else add to this issue.

**Comment by iherman** [comment]
I am fine with that, @fantasai. EPUB is certainly different than printing, so it is o.k. to have rules that are relevant for EPUB only. 

It would be good to have a selector that could be used to select a paged but not printed media...

**Comment by fantasai** [comment]
Some of these are also about page size -- if you have large pages and short sections, breaking on every h2 looks weird. :) See also http://www.w3.org/TR/mediaqueries-4/#mf-overflow-block ; review comments welcome on www-style ;)
