### ISSUE TITLE
Space needed between h1 header and w3c logo

### ISSUE THREAD

**Issue by r12a** [w3c/tr-design#30]
See the image (taken from http://www.w3.org/TR/2015/WD-international-specs-20151020/ with the stylesheet link pointing to the new style sheet)

![screen shot 2015-11-11 at 07 32 29](https://cloud.githubusercontent.com/assets/4839211/11086209/b8f77722-8846-11e5-8191-ab78adedd10f.png)

**Comment by fantasai** [comment]
Should be fixed now.

**Comment by r12a** [comment]
It doesn't seem to be. But then i may be linking to the wrong version of the style sheet. Which one are we supposed to be linking to? (And can we make it a single authoritative location that is on GH or the W3C site?)

**Comment by fantasai** [comment]
The GH repo copy is the authoritative version. I'm just hosting a copy on my site because it'll serve it up correctly, whereas GH is mainly useful for admiring the source code. Replacing the URL with today's copy of http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/W3C-NOTE works for me, closing unless you're seeing something different?

**Comment by r12a** [comment]
i don't see any difference.

![screen shot 2015-12-02 at 14 26 57](https://cloud.githubusercontent.com/assets/4839211/11533303/d7587caa-9900-11e5-895b-318b6add0191.png)

**Comment by fantasai** [comment]
Sorry, I misunderstood the issue. :( Should be fixed now.
