### ISSUE TITLE
Reduce the line spacing in the TOC

### ISSUE THREAD

**Issue by r12a** [w3c/tr-design#32]
I think that a smaller line spacing in the TOC helps to
[1] make the structure of the document easier to see
[2] makes it easier to find items
[3] makes the TOC more compact which helps get a better overview of the document by fitting more into the space available

Compare the following screen snaps, before and after applying the new styling:

![screen shot 2015-11-11 at 07 45 45](https://cloud.githubusercontent.com/assets/4839211/11086408/a325bd26-8848-11e5-9931-31582bcd7d2a.png)

![screen shot 2015-11-11 at 07 45 22](https://cloud.githubusercontent.com/assets/4839211/11086412/a67eeb8c-8848-11e5-9c26-19de2d107dfd.png)

I think the former is more useable.

In addition, the positioning of the numbering in the new style is inconsistent, with the fourth-level numbering drifting to the right.

**Comment by fantasai** [comment]
Done. Not quite as compressed as before, but certainly a bit less loose. Let me know what you think.

**Comment by r12a** [comment]
much better, thanks. 

since you didn't mention it, i assume that the positioning of the numbering isn't going to change?

**Comment by r12a** [comment]
Unless i'm using the wrong style sheet, this problem has returned after being fixed back in November, and if anything the gaps look wider.  Can we refix this please? (Such wide gaps between toc lines and the consequent overall length of the TOC make it harder to see the overall document contents and requires more scrolling to find things which is irritating.)

**Comment by r12a** [comment]
i suggest changing 1.5em in

.toc > li {
    margin: 1.5em 0;
}

at line 965 of base.css to 0.5em

**Comment by fantasai** [comment]
So the rule you're actually looking for is margin: 0.3em 0, which is further down. (Together with padding and line-height, the total spacing between items is about 0.5em.) I adjusted the spacing back up because some other people felt it was too tight. I did reduce the space between lines of wrapped text, however, and this combination makes it much easier to navigate the narrow sidebar ToC when there are long section titles that wrap.

Overall the line spacing in the specs is looser than before, and the line height in the ToC is set to match that. (Note that the CSSWG specs have been using this spacing for awhile now.)

Fwiw, I've put together a comparison of two options here for comparison:
  http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sampleA#toc (~1.5 line-spacing)
  http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sampleB#toc (~1.3 line-spacing)

I'm open to changing it, if that's the consensus, but I think we should hear from more people. In any case I do think we should keep the ToC and body text spacing consistent, though.

**Comment by r12a** [comment]
thanks. Option A looks best to me.

(Btw, i'm don't think there's any real reason to keep the line leading in the TOC and body the same – if function dictates a need for a difference, then that's fine by me. But i'm happy with what i see in option A anyway. It's much better than previously.)

**Comment by fantasai** [comment]
Okay, closing this issue. Feel free to reopen if you think we should re-evaluate!
