### ISSUE TITLE
/TR/ table contrast problem with dark mode

### ISSUE THREAD

**Issue by shawna-slh** [w3c/tr-design#360]
Info in this [LinkedIn post](https://www.linkedin.com/posts/ramy-gamal-797939157_w3c-web-accessibility-initiative-wai-please-activity-7269579512852463616-Xkoj)

**Comment by deniak** [comment]
I took a look at the issue and this is not related to the TR design. That [spec](https://w3c.github.io/aria/#button) is using a custom common.css that forces the background-color of table headers to gray (#eee): https://github.com/w3c/aria/blob/main/common/css/common.css#L92

So that stylesheet needs to be updated to either remove that rule or update the background-color under the dark mode.

**Comment by deniak** [comment]
I opened the issue on the aria repo: https://github.com/w3c/aria/issues/2397
