### ISSUE TITLE
Using dated version is not great

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/tr-design#52]
Can I kindly ask that we refrain from using a year (e.g., "2016") for the directory that holds the redesigns? Using years is known to be problematic (the W3C in particular should know this, as it has a long legacy of using dated URLs poorly). Instead, please tag versions using git and please just use two directories: 

That is, if a resource is stable:
https://www.w3.org/StyleSheets/TR/

Otherwise, it's experimental and should go here: 
https://www.w3.org/StyleSheets/TR/experimental/

Having dated versions makes a huge mess for tools like ReSpec because it means we need to unnecessarily maintain a list of all the possible different experimental versions year over year. Which is a maintenance burden. 

If a user wants to opt into "experimental", then they can just set a flag in ReSpec's conf. However, right now, we are having to special case an `useExperimentalStyles` options using either a boolean or a year. 

If we keep using a year, we are going to make "useExperimentalStyles" just default to 
`new Date().getFullYear()` and hope for the best ... which would be sad.

**Comment by fantasai** [comment]
The style sheets need to be dated so that a spec generated one year can use the style sheets it was generated to work with. What will happen March 1st is that all specs MUST link to the appropriate style sheet in https://www.w3.org/StyleSheets/TR/2016/ ... it will no longer be experimental, and will be required by pubrules.

**Comment by marcoscaceres** [comment]
Doesn't that effectively mean we will end up with a hodgepodge of specs that are all styled differently depending on when they were published? That seems less than ideal. Can't we evolve the style over time?

**Comment by fantasai** [comment]
Yes, that's what it means for rarely-updated or frozen specs, unfortunately. However, I'm hoping the differences between specs will be sufficiently subtle across most years that it won't be too garish...

We can't evolve the style over time because nobody is maintaining archived documents, so can't check that the new style didn't break anything in the old docs. Our publishing rules aren't simplisticly rigid enough for us to be able to predict the kinds of things that might break--this was a major problem with a previous attempt at redesigning the TR docs, in which W3C did try to restyle old specs--and was forced to revert.

See https://github.com/w3c/tr-design/blob/gh-pages/README.md

Going forward, I'm hoping to do a huge breaking redesign sometime in the next couple years, to clean up the horrid amounts of unergonomic boilerplate we have to deal with; but otherwise keep to minor changes across years.

**Comment by marcoscaceres** [comment]
@fantasai thanks for the clarification. Ok, can we please then assure that dirs 2017, 2018, etc. become available year over year. This will allow ReSpec to opt into "latest experimental" without needing to specify a particular style year. I'll support explicitly opting into a year also in ReSpec, but will default to `new Date().getFullYear()`.

**Comment by fantasai** [comment]
I think that's a question for @plehegar ...

**Comment by tripu** [comment]
> Ok, can we please then assure that dirs 2017, 2018, etc. become available year over year. This will allow ReSpec to opt into "latest experimental" without needing to specify a particular style year. I'll support explicitly opting into a year also in ReSpec, but will default to `new Date().getFullYear()`.

Automatically associating `useExperimentalStyles` to the _next_ year (right?) in ReSpec sounds good to me, @marcoscaceres. The caveat is that the cutoff date from year to year will vary (see our two consecutive delays this year). This year, for example, starting 1 January one would assume that `useExperimentalStyles` should point to the 2017 version (the next one being developed). But still today (28 Feb) `useExperimentalStyles` still means `2016`, since we haven't rolled out the update yet&hellip;
