### ISSUE TITLE
Could someone fix some errors flagged by Tenon.io?

### ISSUE THREAD

**Issue by StommePoes** [w3c/tr-design#61]
Tenon has found a few errors which, if fixed, would improve this example of this repo:
http://tenon.io/testNow.php?url=http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sample

The images in the figures need alt, and there are a few duplicate id's. I would at least have an offscreen th in the table like &lt;th&gt;&lt;span class-for-offscreen&gt;property name&lt;/span&gt;&lt;/th&gt;.

**Comment by thierryk** [comment]
As a side note, Steve Faulkner [told me](https://twitter.com/thierrykoblentz/status/694931917582381058) once that images in a `figure` do not necessarily _need_ `alt`, but those images should definitely not be wrapped in a paragraph, see [4.7.1.1.16 When a text alternative is not available at the time of publication](https://www.w3.org/TR/html5/embedded-content-0.html#when-a-text-alternative-is-not-available-at-the-time-of-publication).

**Comment by StommePoes** [comment]
I had run into a lot of discussion about figures, imgs, and alts, but many of them were old and I'd wondered if since 2010 the semantics had changed or support had gotten better, so I checked the specs (they don't _say_ but all examples (maybe happen to) have alts) and asked in the gitter Slackers channel.  After that I did post this issue, as it seems ATs will still notice there is an image and NOT consider the figcaption to be its name. We definitely do not want alt="" here, since then what is the figcaption captioning? So not recommending the empty alt at all.

Although actually I might retest this today and see who does and does not read out the src URL, that would be handy knowledge.

**Comment by thierryk** [comment]
>  I checked the specs (they don't say but all examples (maybe happen to) have alts) 

Did you check [4.7.1.1.16 When a text alternative is not available at the time of publication](https://www.w3.org/TR/html5/embedded-content-0.html#when-a-text-alternative-is-not-available-at-the-time-of-publication)? It shows a couple of examples without `alt`. But from my understanding, this is only ok when it is not possible to include meaningful `alt` values at the time of publication&mdash;it's not a free pass to omit `alt` whenever we use a image in a `figure`.

>  I might retest this today and see who does and does not read out the src URL, that would be handy knowledge.

I agree, please share the results...

**Comment by fantasai** [comment]
I fixed some stuff. The rest of the comments seem stupid. Critical error for putting code in PRE. Poor alt text for some unspecified reason (either too long or too many parentheses, perhaps). And where in the WCAG does it say that the title and alt must be identical. That's stupid. I'm ignoring this tool from now on.

**Comment by StommePoes** [comment]
Did you read what it says for PRE? "The PRE element should be avoided except for cases where pre-formatting makes sense, such as in the case of code examples." This looked clearly to me like a code example (and therefore not an error), and the automated tool caused a human who can tell the difference to take a look and confirm or deny it.

**Comment by karlgroves** [comment]
> I'm ignoring this tool from now on.

Hi, Fantasai,

You can obviously ignore Tenon. Or, you can send me feedback directly on things you disagree with.

As a company, there is no other accessibility tool vendor that accepts - and seeks - feedback as eagerly as we do.  We do it in our documentation [1], on Twitter [2], our Facebook page[3], and our recorded webinars[4].  

We also directly email our users periodically to prod them for feedback. Every email we send - including automated ones - either come from me personally or from our 'talktous@tenon.io' email which also goes directly to me, and my personal mobile phone number is on every single page of the site. The contact page has my phone number and email, and the support form goes directly to me as well.   Simply put, you will not find an accessibility tool vendor that offers the same level of access to those who run the company and make the tool than Tenon.

Now, let's go over these issues one-by-one
1. "Image has alt & title that are different".  You said " And where in the WCAG does it say that the title and alt must be identical."

Actually, that's not what Tenon claims, at all. Tenon says "This image has both an alt attribute and title attribute, but the text within them is different. A single, useful alt attribute should be provided for this image."

This is true. According to the accessible name calculation rules followed by most ATs and defined by the W3C's PFWG[5] the alt attribute takes precedence over title. So the question I'd ask is this: Is there content in the title attribute that you want the user to have access to? If so, then it needs to be in the alt because otherwise it will get ignored.  If you don't want the user to access it, then why is it even there in the first place?

2&3: "Potentially poor alt attribute found" - This is tID45 which looks for alt attributes that are too long.  The threshold for this is 100 characters. This is, frankly, our own subjectively determined threshold. The alt attribute used to have a functional limitation of about 100 characters but that was a long time ago. However it begs the question: what useful alt text is > 100 characters?  If the average word in English is 5 letters, this means your alt is around 20 words.  Maybe this check is too strict. Maybe we should double the threshold. I'm certainly open to considering it if others find it too strict as well. But at some point you have to consider whether moving that lengthy alt into a caption might be better.

4: "Preformatted text found". As Mallory mentioned, tID 35 looks for `pre` element without `code` element inside it. We actually have a bug entry around this to improve it. The issue number in Jira is TEN-1103 and the suggested change is that we add an additional check to see if there's a large number of encoded entities in the `pre` element.  What do you think of that change?

I'd like to encourage you and anyone else who comes across this discussion to send feedback any time - up to and including calling me directly on the telephone.  If you have criticisms, I want to hear them, because I want my product to be the best, and everyone who knows me knows that's not just lip service. 

Thanks.

1 - http://tenon.io/documentation/understanding-issue-reports.php#what-do-i-do-if-i-disagree-with-a-test-result
2 - https://twitter.com/TenonAPI/status/702318568533315584
3 - https://www.facebook.com/tenonAPI/
4 - https://www.youtube.com/watch?v=d_ZsXr0da_k
5 - https://www.w3.org/TR/accname-aam-1.1/

**Comment by StommePoes** [comment]
I maybe also should apologise to @fantasai for throwing the results of some tool the developers didn't know about or research into an Issue, since only with an API key do you get links to where in the WCAG the tool may be referring to or why it suggests some things. The reason I did post it was because a lot of them were the obvious-type errors and the tool lists line numbers and a description which I thought was handier than copying them over by hand myself.

For @thierryk I may just post a link to figure results here later so as not to further clutter a closed issue.

**Comment by fantasai** [comment]
The alt attribute is intended to be a replacement for what the image conveys. Capping it at any amount of text seems counter-productive. (In fact the IMG tag should have worked like OBJECT which can contain arbitrary content, including markup. But we can't fix that at this point.) But let's say you want a cap. Wouldn't 1000 words be the appropriate cap, given that it's common knowledge that a picture is worth 1000 words? 100 characters is way insufficient, even in Chinese.

PRE being noted isn't a problem, but being a critical error is a problem. If it's about "Make sure this thing is used correctly", that's a warning. Not the highest-possible-scoring error -- that should be for "you are absolutely wrong here and you must fix this" type errors.

“Actually, that's not what Tenon claims, at all. Tenon says "This image has both an alt attribute and title attribute, but the text within them is different. A single, useful alt attribute should be provided for this image."”

If Tenon isn't upset about the alt and title being different, then it shouldn't be complaining about that fact in its error message.

“So the question I'd ask is this: Is there content in the title attribute that you want the user to have access to? If so, then it needs to be in the alt because otherwise it will get ignored. If you don't want the user to access it, then why is it even there in the first place?”

If this is your position, then please petition the HTMLWG to make the title attribute on <img> elements a conformance error, and reword your error to say that "Using title attributes is forbidden in a11y best practices."

**Comment by StommePoes** [comment]
@thierryk Basic results: JAWS and NVDA on both IE and FF act as though the images are alt="". Bad because acts as if figure is empty with just the caption.
Orca/FF knows there are images, but gives nothing else away.
VO is reading out the image names, but not the full nausea-inducing URLs (yay, and thanks to my iThing-owning testers for their help).
http://stommepoes.nl/work/figures.html

**Comment by thierryk** [comment]
@StommePoes 

wow! It seems somebody missed the memo because [4.7.1.1.16](https://www.w3.org/TR/html5/embedded-content-0.html#when-a-text-alternative-is-not-available-at-the-time-of-publication) says:

> In some cases an image is included in a published document, but the author is unable to provide an appropriate text alternative. In such cases the minimum requirement is to provide a caption for the image using the `figure` and `figcaption` elements. [...]. The only content of the `figure` [must be] an `img` element and a `figcaption` element, and the `figcaption` element must include (caption) content.

That's why accessibility is more about _best practices_ than specs. In the context of this thread, it'd be about not using _both_ `alt` and `title` on images.

Thanks a lot for sharing these results.

**Comment by StommePoes** [comment]
@thierryk I'm confused. 
1. I don't recall, were there initially titles on those images? I thought not, but now I'm doubting...
2. I don't see any mention either way of title in that page you reference. Would having a title in an example such as my tests above be a violation?
3. I can't see how this document can ever fit the case of "the author is unable to provide an appropriate text alternative"-- these aren't automatic uploaded photos or anything, it's a spec document. Someone's choosing the images for a reason and there are humans looking at it, not just a Flickr robot.

And yes, I see the current code would be incorrect without alts if it wanted to consider itself as adhering to 4.7.1.1.16 because there are still p tags wrapping the images, but since there's now alts on them it's no longer an issue, right?

Also, I don't see the point in saying one thing to users encountering ALT and something different for those privileged to have access to TITLE. But I see that as a content-writing/audience decision and since I can't get to titles as a user I don't really care.

**Comment by thierryk** [comment]
@StommePoes 

> I'm confused.

The reference I made to `title` and `alt` was not related to our discussion about `figure` but to what Tenon  found and what @karlgroves said in his comment above (`alt` _alone_ should be used).

> adhering to 4.7.1.1.16 because there are still p tags wrapping the images

Correct. But in any case, I don't really see a reason for wrapping that image in `figure` inside a paragraph... 

> Also, I don't see the point in saying one thing to users encountering ALT and something different for those privileged to have access to TITLE

Yes, that's what I'm referring to when I say &quot;In the context of this thread ...&quot;

**Comment by StommePoes** [comment]
Ah, gotcha. Thanks!

Note: my last sentence I should have separated more-- most of the comment was in reply to you. The last one was a general statement about how titles suck horribly almost all the time... but that's not a spec-anything.
