### ISSUE TITLE
Small bug with tabs in ToC

### ISSUE THREAD

**Issue by halindrome** [w3c/tr-design#64]
There is a bug - the collapse sidebar button can be made to stick on.  I attached a video that I hope works.  You can also see it (in severely reduced resolution) at https://youtu.be/_rcvgbV-XsAsA

**Comment by fantasai** [comment]
Ah, this is a tricky one. That link stays visible (and tall enough to put the text over the status text) so long as it's focussed. I suspect this will be resolved now that https://bugs.chromium.org/p/chromium/issues/detail?id=454172#c22 is fixed, since it doesn't seem to be a problem in Firefox. Let me know if that's not the case?
