### ISSUE TITLE
Logo does not appear when printing

### ISSUE THREAD

**Issue by halindrome** [w3c/tr-design#77]
When I print a spec using the new styles, the logo appears as an outlined box with no content.

**Comment by halindrome** [comment]
Note sure what can be done about this.  It is because it is in the background I think.

**Comment by tripu** [comment]
I don't have a printer here now, but I `Ctrl+P`'d [`w3.org/TR/2016/WD-html-aria-20160310`](https://www.w3.org/TR/2016/WD-html-aria-20160310/) and looked at both the preview and the &ldquo;printed&rdquo; PDF.
- Chromium shows the logo OK in both cases.
- Firefox does not.

**Comment by marcoscaceres** [comment]
It also fails to print in Safari.

**Comment by marcoscaceres** [comment]
It is something to do with the background color of the SVG not being set?

**Comment by marcoscaceres** [comment]
Actually, it looks like the `@print` media query has been "x"-ed out:

``` css
    @media print {
        rect {
            xfill-opacity: 1;
               }
    }
```

**Comment by fantasai** [comment]
That's clearly a typo. :(

**Comment by tripu** [comment]
Same here (fails only on FF, as before).

FF sends this header in the request for the image:
`Accept: image/png,image/*;q=0.8,*/*;q=0.5`
while Chrom\* sends
`Accept: image/webp,image/*,*/*;q=0.8`
I think that's why FF is getting the PNG version (and not printing it), while Chrom\* gets the SVG (that @fantasai already fixed).

Reopening.

**Comment by halindrome** [comment]
Umm.... I am using Chrom\* and it doesn't print.

**Comment by tabatkins** [comment]
Rather, _all_ browsers _are_ printing the image.  The image is just white-on-transparent, which when put on a white background, makes it invisible.  When displayed on-screen, the stylesheet puts a background-color on the `<img>`, but background colors are disabled when printing.  The SVG just has a print stylesheet that's supposed to fix this, but obviously that doesn't work for PNG.

There is a property to fix this - if you set [color-adjust: exact](https://drafts.csswg.org/css-color/#color-adjust) on the image, it _should_ preserve the background-color.  Dunno what browser support is for that.

But really, the only reason we're getting into this situation (a white-on-transparent image that requires the spec to apply a background-color on the `<img>`) is to apply a subtle hover effect on the logo - if you hover it, it gets slightly lighter.  This is a hacky way to achieve this effect, and it causes problems, as we see.

A better way to handle this is to put a background on the image, so it's readable/printable by default, then use something like `filter: brightness(110%);` on hover.  That'll achieve the desired effect on supporting browsers, and since this is just a minor cosmetic detail, falling back to not working on some browsers is totally fine.

**Comment by fantasai** [comment]
Alternately, if the browsers handled @media print when printing embedded SVG images, as opposed to only when loading the image by itself, that would solve the problem. :) Given bugginess, however, filters do seem like the best way to go.

**Comment by tabatkins** [comment]
Handling @media doesn't help the PNG version. ^_^

Anyway, +1 on the fix, thanks.
