### ISSUE TITLE
fixup.js adds "overlarge" wrapper to *all* data tables, breaking their appearance

### ISSUE THREAD

**Issue by tabatkins** [w3c/tr-design#86]
https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/WebBluetoothCG/web-bluetooth/gh-pages/index.bs#example-filter-by-services has a table that fits into the example area just fine, but fixup.js wraps it in a `<div class=overlarge>` which automatically makes it stretch to fill the entire page, which looks really dumb.

**Comment by fantasai** [comment]
Okay, so I pushed a couple changes that will make this better:
1. Added 'max-width: 50em' to tables wrapped in .overlarge. I think this was the original intention: it keeps them from overflowing the max-width unless the need the room, while .overlarge gives them their own scroller in case they overflow the screen.
2. Removed the automatic .overlarge wrapper around anything inside a colored box, since it'll be weird there and such tables are unlikely to need the extra space anyway.

I thought about removing the 'width: 100%' from the data tables, but it was put there so nearby tables of similar structure are guaranteed the same width.

The main fix here is #1. Let me know if you think I should revert #2. And if you have any other thoughts on this issue.
